language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - composer update --prefer-source --prefer-lowest --prefer-stable

script: 
  - composer install
  - phpunit