language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
sudo: false
before_script:
  - composer update --prefer-source --prefer-lowest --prefer-stable
script: 
  - composer install
  - phpunit
notifications:
  email: false